### ISSUE TITLE
will deprecate vagrant-quick-start

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/akashic-storage#108]
We have open storage, so this is useless

**Comment by akiradeveloper** [comment]
or what we need is ansible? or Dockerfile?

**Comment by kiaking** [comment]
I think it's nice idea to keep Vagrant because I think some people want to actually develop, configure and test the app within VM.

**Comment by akiradeveloper** [comment]
@kiaking They have their own VM to develop their app and installing akashic-storage there is enough. So there is no reason to provide Vagrant.

it's not quite soon to remove this so we have time to discuss face to face. See you later.

**Comment by akiradeveloper** [comment]
admin-web should be installed (with admin-cli accordingly)

**Comment by akiradeveloper** [comment]
I think I will lift the vagrant-s3-tests/Vagrantfile to the top level. Once use type `vagrant up` and the server is up with daemon, admin-cli and admin-web set up. This is amazing

**Comment by akiradeveloper** [comment]
I realize that web programmers don't care about the performance difference between host machine and the VM. I think they never install akashic-storage into the host machine.

**Comment by akiradeveloper** [comment]
Vagrantfile is lifted to top level and admin-web is responding after vagrant up is done.
