### ISSUE TITLE
How about renting VPS and provides real quick-starting

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/akashic-storage#6]
The cheapest one is 500 yen for month so it's payable for me.

Problem is malicious user will try to crack the server and he/she uploads Gigantic files so other users are affected. Some mechanism to throttle uploading per user is required (and a cleaner of course!)

**Comment by kiaking** [comment]
Maybe set maximum upload limit and throttling feature...? Maybe you could use Nginx to proxy akashic-storage and let Nginx take care of those stuffs (I don't know if Nginx has throttle though).

**Comment by akiradeveloper** [comment]
Since we have Vagrant, this isn't high-priority issue.

**Comment by akiradeveloper** [comment]
I will rethink bout this after v1.0-rc

**Comment by akiradeveloper** [comment]
I lent a server!

**Comment by akiradeveloper** [comment]
As you may notice, there is open-storage built on VPS http://27.120.80.37:10947/
