### ISSUE TITLE
Vagrant tries to mount wrong directories on reload

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/akashic-storage#8]
Although it mounts correctly on the initial up but after reload (or halt/up), the mounting goes crazy.

```
==> default: Mounting shared folders...
    default: /vagrant => /Users/akira/share/fss3/vagrant-quick-start
```

**Comment by akiradeveloper** [comment]
Does Vagrant always try to mount /vagrant to current directory?
If so, should be disabled.

**Comment by kiaking** [comment]
> Does Vagrant always try to mount /vagrant to current directory?

Yes. It can be disabled like this.

``` ruby
config.vm.synced_folder ".", "/vagrant", disabled: true
```

See here https://www.vagrantup.com/docs/synced-folders/basic_usage.html (DISABLING section).

**Comment by akiradeveloper** [comment]
Oh great. You can send me a PR

**Comment by kiaking** [comment]
Gotcha.
